version: 2.1

commands:
  setup_env:
    steps:
      - run:
          name: Setup environments
          command: |
            ARR=("v1 v2 v3")
jobs:
  build:
    working_directory: ~/src
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - setup_env
      - run:
          name: Simple check ETL integrity
          command: |
            ls -la
            VALS="v1 v2 v3"
            echo $VALS
            echo '>>>>'
            for v in $VALS; do
              echo $v;
            done