version: 2.1

commands:
  setup_env:
    steps:
      - run:
          name: Setup environments
          command: |
            ARR=(v1 v2 v3)
            echo "export VALS=`echo ${ARR[*]}`" >> $BASH_ENV
            source $BASH_ENV
jobs:
  build:
    working_directory: ~/src
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - setup_env
      - run:
          name: Simple check ETL integrity
          command: |
            ls -la
            echo $VALS